apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
        - image: isal20/microblog:latest
          name: microblog
          resources:
            requests:
              cpu: 250m  
            limits:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 15
          ports:
            - containerPort: 5000
              name: microblog 
          env:
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secrets
                  key: DB_PASSWORD
            - name: DATABASE_URL
              value: "mysql+pymysql://microblog:${DB_PASSWORD}@mysql/microblog"

