---
- name: Run node exporter container
  docker_container:
    name: node_exporter
    image: prom/node-exporter:v1.2.2
    state: started
    restart_policy: unless-stopped
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
        - "9100:9100"
    
    