global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ["{{ groups['monitoring'][0] }}:9090"] 

  - job_name: "appServer"
    static_configs:
    - targets: ["{{ groups['appServer'][0] }}:9100"]

  - job_name: "flask"
    static_configs:
    - targets: ["{{ groups['appServer'][0] }}:8000"] 

  - job_name: "nginx"
    metrics_path: /prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["{{ groups['monitoring'][0] }}:9113"]

 