---
- name: Install packages 
  apt:
    name: 
      - nginx
      - python-certbot-nginx
    state: present

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
  register: letsencrypt_cert

- debug: msg="{{ letsencrypt_cert.stat.exists }}"

- name: Stop services to allow certbot to generate a cert
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - nginx
  when: letsencrypt_cert.stat.exists == False

- name: Generate new certificate if one doesn't exist
  command: "certbot certonly --standalone --noninteractive --expand --agree-tos --email {{ admin_email }} -d {{ domain_name }} -d www.{{ domain_name }}"
  when: not letsencrypt_cert.stat.exists

- name: Remove default conf
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Copy nginx conf
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy load balancer conf
  template:
    src: ../templates/load-balancer.conf.j2
    dest: /etc/nginx/sites-available/load-balancer.conf
  
- name: Create symlink to load balancer conf
  file:
    src: /etc/nginx/sites-available/load-balancer.conf
    dest: /etc/nginx/sites-enabled/load-balancer.conf
    state: link

- name: Validate nginx config
  command: nginx -t

- name: Start nginx
  service:
    name: nginx
    state: started 
    enabled: yes

