FROM python:3.10-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
COPY gunicorn_config.py gunicorn_config.py

RUN python -m venv .venv && \
    . .venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

COPY app app
COPY migrations migrations

ENV FLASK_APP microblog.py

RUN chmod +x boot.sh && \
    chown -R microblog:microblog . 

USER microblog

ENV prometheus_multiproc_dir /tmp 

EXPOSE 5000

ENTRYPOINT ["./boot.sh"]
