FROM python:3.10-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv && \
    . .venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt


ENV FLASK_APP microblog.py

RUN chmod +x boot.sh && \
    chown -R microblog:microblog . 

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]