---
- name: Copy prometheus config file
  template:
      src: ./templates/prometheus.yml
      dest: /tmp/prometheus.yml

- name: Create a docker volume for prometheus
  docker_volume:
    name: prometheus_data
      
- name: Run prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:v2.31.1
    state: started
    restart_policy: unless-stopped
    network_mode: host
    recreate: yes
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=24h"
      - "--web.enable-lifecycle"

      
    