---
- name: Start mysql docker container
  docker_container:
    name: mysql
    image: mysql/mysql-server:5.7
    env:
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "microblog"
    ports:
      - "3306:3306"
    restart_policy: always
  