name: Build and push Docker images
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: sumca252/microblog
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
            custom=${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile_prod
          push: true
          tags:  isal20/microblog:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  
  